version: '3.7'
services:
    database:
        image: mysql:5.7
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: main
        ports:
            - '3306:3306'
        networks:
            - check24App              

        volumes:
        - dbdata:/var/lib/mysql            
 

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - database
        environment:
            PMA_HOST: pma
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8082:80
        networks:
            - check24App          

volumes:
  dbdata:                                   

networks:
  check24App:
    driver: bridge